#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net slapd
}

start() {
	ebegin "Starting mmc-agent"
	eval start-stop-daemon --start --quiet --exec /usr/sbin/mmc-agent --pidfile /var/run/mmc-agent.pid 
	eend $?
}

stop() {
	ebegin "Stopping mmc-agent"
	start-stop-daemon --stop --quiet --pidfile /var/run/mmc-agent.pid 
	eend $?
}
